### ISSUE TITLE
Store, updated and delete takes seconds to affect elasticsearch

### ISSUE THREAD

**Issue by yashiroiori** [babenkoivan/scout-elasticsearch-driver#169] opened 2018-12-18 03:23 UTC
Hi, when delete an item, after search again to refresh a table, but when search the item deleted appear without deleted, an a seconds after are refreshed in elasticsearch.
How do to get a refreshed list of search when store, update and delete??

```
public function destroy($id)
    {
        return DB::transaction(function () use ($id) {
            $metricCustom = MetricCustom::findOrFail($id);
            $name = $metricCustom->name;
            $metricCustom->delete();
            return response()->json([
                'message'=>'Unidad de medida personalizada: '.$name.' eliminada',
                'uomCustoms' => MetricCustom::search('*')->orderBy('name')->get(),
            ]);
        });
    }
```

**Comment by iget-esoares** [comment] 2019-03-21 22:09
This is actually how Elasticsearch works. Since it main concern is to respond fast to searches, it doesn't update the index in real time, but it's near real time.

See [this Stackoverflow question](https://stackoverflow.com/questions/31499575/how-to-deal-with-elasticsearch-index-delay).

To have immediate indexing, you must set the `SCOUT_ELASTIC_DOCUMENT_REFRESH` env variable to `wait_for` in your .env file, or change the `scout_elastic.document_refresh` config to `wait_for`.

Closing this issue since it's not a bug. Feel free to open a new one if you find any bug or have any feature request.

**Closed by iget-esoares** 2019-03-21 22:09 UTC
