### ISSUE TITLE
Types provide error

### ISSUE THREAD

**Issue by vishnuvg1984** [babenkoivan/scout-elasticsearch-driver#236] opened 2019-05-31 19:22 UTC
Hi Baben,

We are using scout-elasticsearch driver. We recently moved our server to a new environment. Some how the elastic search version in Laravel got updated to 7.1.1 and getting error 

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}

The mapping we used is protected $mapping = [
        'properties' => [
            'id' => ['type' => 'text'],
            'firstname' => ['type' => 'text'],
            'lastname' => ['type' => 'text']
        ],
    ];

The error happens while we update the index. Appreciate if any suggestion to recover.

**Comment by rvkolosov** [comment] 2019-06-03 18:45
Set  SCOUT_ELASTIC_UPDATE_MAPPING=false in .env file, and delete $mapping from your Model.
After that recreate index file for elasticsearch, its work for me.

**Comment by superern** [comment] 2019-06-17 07:27
> Set SCOUT_ELASTIC_UPDATE_MAPPING=false in .env file, and delete $mapping from your Model.
> After that recreate index file for elasticsearch, its work for me.

tried, does not resolve my issue

**Comment by rvkolosov** [comment] 2019-06-17 07:33
> > Set SCOUT_ELASTIC_UPDATE_MAPPING=false in .env file, and delete $mapping from your Model.
> > After that recreate index file for elasticsearch, its work for me.
> 
> tried, does not resolve my issue

Did you call?

> php artisan config:cache

**Comment by Surt** [comment] 2019-06-17 16:42
Hi guys, I can't set it to work,

I did started from a clean elastic 7.1.1
* create-index
* update-mapping  // Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.
* scout import 

I did set `SCOUT_ELASTIC_UPDATE_MAPPING=false' without laravel cache, but it does not work.

**Comment by rvkolosov** [comment] 2019-06-17 19:32
> Hi guys, I can't make it work,
> 
> I did started from a clean elastic 7.1.1
> *1 create-index
> *2 update-mapping
> *3 scout import
> 
> 2 causes the error Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.
> 
> I did set `SCOUT_ELASTIC_UPDATE_MAPPING=false' without laravel cache, but it does not work.
> 
> If I execute 1 and 3 only, the mappings are not set on the elasticsearch index. (My nested types are not there)

https://github.com/babenkoivan/scout-elasticsearch-driver/issues/235#issuecomment-496813375

**Comment by babenkoivan** [comment] 2019-06-20 13:30
Hi, ES 7 isn't yet supported. I'm closing this as a duplicate of https://github.com/babenkoivan/scout-elasticsearch-driver/issues/214

**Closed by babenkoivan** 2019-06-20 13:30 UTC
