### ISSUE TITLE
Set the size parameter of a query.

### ISSUE THREAD

**Issue by greggh** [babenkoivan/scout-elasticsearch-driver#228] opened 2019-05-21 16:06 UTC
I can't figure out where to pass in the size parameter. I am using this in an app that is 90% inside of Nova. It works great, but all of my searches are limited to 200 results. I would like to get a lot more.

Queries are passing in size:200.  I would like to change that to 10000. How can I do that here?

**Comment by iget-esoares** [comment] 2019-05-25 19:09
Really can't understand your question. Could you post some code?

**Comment by greggh** [comment] 2019-05-27 00:12
I'm not sure how to explain it better. Nova searches via scout if its there. Scout is using this plugin, it's working great.

But its only returning 200 results. I need more results or pagination or something. Because there are a lot of results.

I can't really post much in the way of code, the scout integration is all built into Laravel Nova. It sees Searchable, it uses it.

**Comment by clovenlife** [comment] 2019-05-27 00:26
Sounds like your issue is with Nova and how it implements scout, both are well outside the scope of this package. 
You might make sure you have nova configured correctly https://nova.laravel.com/docs/1.0/resources/#pagination

**Comment by greggh** [comment] 2019-05-27 00:34
@clovenlife 

Could be, if you're telling me that Nova is setting the 200 record limit with the size parameter of the elastic search query.

Here is an example from my slowlog:

```
[2019-05-21T11:41:53,958][TRACE][index.search.slowlog.query] [node-1] [domain][3] took[469.7ms], took_millis[469], total_hits[2621], types[domains], stats[], searc h_type[QUERY_THEN_FETCH], total_shards[5], source[{"size":200,"query":{"bool":{"should":[{"wildcard":{"domain":{"wildcard":"*gmail*","boost":1.0}}}],"adjust_pure_n egative":true,"boost":1.0}}}], id[]
```

I am referring to the "size":200 part of the source there. That seems to be coming from this driver, not Scout or Nova. I have no settings for Scout or Nova for a limit and nothing for 200.

This driver is awesome, thanks for everything you've built. I just need to figure this one out, and so I guess the first thing I need to know is if this driver is setting that 200 limit. I don't think Nova or Scout has any idea about Elastic Searches size and from parameters, so I have no idea how they could be doing it.

**Comment by clovenlife** [comment] 2019-05-27 01:03
@greggh there is not any code in this driver that defines a default query limit. Scout tells this driver the parameters to search by and all this driver does is translate them into the format required by elasticsearch, and then transforms the results from elasticsearch into an object usable by scout and laravel.

The only other place a query limit could be coming from would be defined in a search rules template you would have created.

**Comment by greggh** [comment] 2019-05-27 01:04
@clovenlife makes sense. I don't have a limit in my search rules, I didnt even know that was possible.

Ok, so then this is probably a Nova -> Scout related bug where it isn't passing any pagination info to the driver. I'll have to go over there and see what they say.

**Comment by iget-esoares** [comment] 2019-07-02 14:24
Closing this issue since it's not a bug on this package.

Please feel free to ask for a re-open if necessary.

**Closed by iget-esoares** 2019-07-02 14:24 UTC

**Comment by u-michiel** [comment] 2019-10-24 08:44
@greggh Did you find a solution for the size limit?

**Comment by alicompu** [comment] 2021-08-23 08:31
![image](https://user-images.githubusercontent.com/21305305/130415952-c84d6eb9-ee20-4c98-bc1d-46c035c02b3a.png)
I find problem as elastic.
I data record 180000 but show 10000
