### ISSUE TITLE
ErrorException: Illegal string offset 'hits' src/ElasticEngine.php:225

### ISSUE THREAD

**Issue by azcoppen** [babenkoivan/scout-elasticsearch-driver#49] opened 2018-01-15 15:26 UTC
First off - thanks for the amazing package! Using it in almost all my projects. Easily the best!

Getting this error this morning. Laravel 5.5 (Ubuntu), dev-master in composer.json, connecting to  Ubuntu/ES 6.1.

```
PHP 7.2.1-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:54:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.1-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

```
[2018-01-15 15:20:23] production.ERROR: ErrorException: Illegal string offset 'hits' in /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php:225
Stack trace:
#0 /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php(225): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal string ...', '/srv/gbpa.com/a...', 225, Array)
#1 /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php(151): ScoutElastic\ElasticEngine->getTotalCount('<!DOCTYPE html ...')
#2 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Support/Collection.php(337): ScoutElastic\ElasticEngine->ScoutElastic\{closure}(Array, 0)
#3 /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php(154): Illuminate\Support\Collection->each(Object(Closure))
#4 /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php(168): ScoutElastic\ElasticEngine->performSearch(Object(ScoutElastic\Builders\SearchBuilder), Array)
#5 /srv/gbpa.com/api/vendor/laravel/scout/src/Builder.php(224): ScoutElastic\ElasticEngine->paginate(Object(ScoutElastic\Builders\SearchBuilder), 25, 1)
#6 /srv/gbpa.com/api/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php(428): Laravel\Scout\Builder->paginate(25, Array)
#7 /srv/gbpa.com/api/app/Http/Controllers/BaseController.php(57): Prettus\Repository\Eloquent\BaseRepository->paginate(25, Array)
#8 /srv/gbpa.com/api/app/Http/Controllers/GIS/AddressController.php(28): GBPAAPI\Http\Controllers\BaseController->search_by_keyword(Object(Illuminate\Http\Request), 'GBPAAPI\\Transfo...')
#9 [internal function]: GBPAAPI\Http\Controllers\GIS\AddressController->search_by_name(Object(Illuminate\Http\Request))
#10 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('search_by_name', Array)
#12 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(GBPAAPI\Http\Controllers\GIS\AddressController), 'search_by_name')
#13 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#14 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#15 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#38 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#40 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /srv/gbpa.com/api/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 /srv/gbpa.com/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#59 /srv/gbpa.com/api/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#60 {main}
```

**Comment by babenkoivan** [comment] 2018-01-16 16:09
Hey, are you sure that your ES service is running and index is alive?

**Comment by azcoppen** [comment] 2018-01-16 19:23
100%. Example (dev) - https://elastic.gbpa.com/addresses/_search?q=suffolk

**Comment by babenkoivan** [comment] 2018-01-17 14:15
do you get the error with any request to this ES instance? maybe you pass wrong data (non-existing page number or something like this)? try to make simple query with `search` method.

because this string looks really weird :D:

```
#1 /srv/gbpa.com/api/vendor/babenkoivan/scout-elasticsearch-driver/src/ElasticEngine.php(151): ScoutElastic\ElasticEngine->getTotalCount('**<!DOCTYPE html ...**')
```

**Comment by babenkoivan** [comment] 2018-03-12 21:32
No feedback from the author.
The issue is closed as outdated.

**Closed by babenkoivan** 2018-03-12 21:32 UTC
