### ISSUE TITLE
_close not supported by Amazon Elastic Search

### ISSUE THREAD

**Issue by clovenlife** [babenkoivan/scout-elasticsearch-driver#254] opened 2019-07-01 18:43 UTC
**Versions**

- scout-elastic-driver: 4.0.0
- laravel/framwork: 5.8
- php: 7.3
- elasticsearch: 6.5 

**Description**

Running update-index command returns:

     {"Message":"Your request: '/test_index/_close' is not allowed by Amazon Elasticsearch Service."}

**Steps to reproduce**

    run php artisan elastic:update-index App\\MemberIndexConfig
while using ElasticSearch hosted by Amazon Web Services

**Comment by iget-master** [comment] 2019-07-01 18:47
Actually that's an limitation of Amazon Elastic Search. 

The `elastic:update-index` need to be modified to delete the index instead of closing it.

**Comment by iget-esoares** [comment] 2019-07-01 18:48
Actually that's an limitation of Amazon Elastic Search.

The elastic:update-index need to be modified to delete the index instead of closing it.

**Comment by babenkoivan** [comment] 2019-07-01 18:56
You can also use `elastic:migrate` command.

**Comment by iget-esoares** [comment] 2019-07-02 14:10
Please try both suggested workarounds and give us a feedback.

I'm closing this issue for now since it's not a bug on this package.

If you still think this is an issue, feel free to ask me a re-open.

**Closed by iget-esoares** 2019-07-02 14:10 UTC
