### ISSUE TITLE
Laradock + elasticsearch «No alive nodes found in your cluster»

### ISSUE THREAD

**Issue by VictorFursa** [babenkoivan/scout-elasticsearch-driver#206] opened 2019-03-23 13:10 UTC
```
<?php
//scout_elastic.php
return [
    'client' => [
        'hosts' => [
           'elasticsearch',
        ]
    ],

    'update_mapping' => env('SCOUT_ELASTIC_UPDATE_MAPPING', true),
    'indexer' => env('SCOUT_ELASTIC_INDEXER', 'single'),
    'document_refresh' => env('SCOUT_ELASTIC_DOCUMENT_REFRESH')
];
```

```
//scout.php
'driver' => elastic'
```
**ElasticSearch** 
localhost:9200 
{
"name" : "oOa2O2Z",
"cluster_name" : "laradock-cluster",
"cluster_uuid" : "oF0BkqrgToWiVBm3skQOXw",
"version" : {
"number" : "6.6.0",
"build_flavor" : "default",
"build_type" : "tar",
"build_hash" : "a9861f4",
"build_date" : "2019-01-24T11:27:09.439740Z",
"build_snapshot" : false,
"lucene_version" : "7.6.0",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"
},
"tagline" : "You Know, for Search"
}

laradock@307c04d87109:/var/www$ php artisan elastic:create-index App\\Models\\MyIndexConfigurator
**The advert_index index was created!
The advert_index_write alias for the advert_index index was created!**
laradock@307c04d87109:/var/www$ php artisan scout:import "App\Models\Advert"
Imported [App\Models\Advert] models up to ID: 60
**All [App\Models\Advert] records have been imported.**
laradock@307c04d87109:/var/www$ php artisan elastic:update-mapping App\\Models\\Advert
**The advert_index mapping was updated!**
laradock@307c04d87109:/var/www$ php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"
**Publishing complete.**
laradock@307c04d87109:/var/www$ php artisan elastic:create-index App\\Models\\MyIndexConfigurator

`Advert::search('*')->get();`

**Elasticsearch \ Common \ Exceptions \ NoNodesAvailableException
No alive nodes found in your cluster**

**Comment by iget-esoares** [comment] 2019-03-23 14:21
Can you post the result of 

````
curl -X GET "localhost:9200/_cluster/health"
````

When the error occurs?

Looks like a problem on elastic search itself.

**Comment by VictorFursa** [comment] 2019-03-23 14:35
curl -X GET "localhost:9200/_cluster/health"
{"cluster_name":"laradock-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":5,"active_shards":5,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":5,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}

**Comment by iget-esoares** [comment] 2019-03-23 17:10
If you set an invalid host on your `scout_elastic.php` config file, it will also throw this error.

On your sample, you set the host to `elasticsearch`, not to `localhost`.

Not sure why every command work. Looks like you have some problem in your application. The `search` method is the "reason" of this package, and it works as it should.

**Comment by VictorFursa** [comment] 2019-03-24 11:14
I fix my problem 

add in to docker-compose.yml 
      networks:
        - frontend
        **- backend**

and 
### Docker-in-Docker ################################################


### ElasticSearch ########################################
    elasticsearch:
      build: ./elasticsearch
      volumes:
        - elasticsearch:/usr/share/elasticsearch/data
      environment:
        - cluster.name=laradock-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
      depends_on:
        - php-fpm
      networks:
        - frontend
        **- backend**

### Docker-in-Docker ################################################
    docker-in-docker:
      image: docker:dind
      privileged: true
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - 2375
      networks:
        - backend

**Comment by iget-esoares** [comment] 2019-03-24 14:57
Hi @VictorFursa 

Closing this since it's not a bug.

Thanks.

**Closed by iget-esoares** 2019-03-24 14:57 UTC
