### ISSUE TITLE
ElasticSearch version 7.0

### ISSUE THREAD

**Issue by aerjotl** [babenkoivan/scout-elasticsearch-driver#215] opened 2019-04-22 21:35 UTC
Hi guys, 

does the package support ElasticSearch version 7.0?

I had a successful setup with 6.7, but after upgrade to 7.0 I'm getting issues like this:
```
Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
```

and I was not able to overcome them so far. Anyone has any experience to share?

thanks

**Comment by iget-esoares** [comment] 2019-04-22 22:48
Duplicate of #214.

Closing this issue, please visit the #214.

**Closed by iget-esoares** 2019-04-22 22:48 UTC
