### ISSUE TITLE
 php artisan elastic:update-mapping App\Models\Us

### ISSUE THREAD

**Issue by ahxiaowu** [babenkoivan/scout-elasticsearch-driver#253] opened 2019-07-01 15:47 UTC
Elasticsearch\Common\Exceptions\BadRequest400Exception  : {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/users_write/_mapping/us] contains unrecognized parameter: [include_type_name]"}],"type":"illegal_argument_exception","reason":"request [/users_write/_mapping/us] contains unrecognized parameter: [include_type_name]"},"status":400

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use ScoutElastic\Searchable;

use App\Es\UserIndexConf;

class Us extends Model {
    use Searchable;
    protected $indexConfigurator = UserIndexConf::class;

    protected $searchRules = [];

    /*public function searchableAs() {
        return 'users';
    }*/


    protected $mapping = [
        'properties' => [
            'username' => 'text'
        ]
    ];
}
```

**Comment by mathmarques** [comment] 2019-07-01 16:04
Please, update your scout-elasticsearch-driver to version 3.12.

**Comment by iget-master** [comment] 2019-07-02 14:17
@ahxiaowu 

This was a known issue caused by the 7.0 compatibility introduced on 3.11, but since it causes an break change, we reverted it on 3.12 and released the 7.0 support on 4.0.

As suggested by @mathmarques update you dependencies to have scout-elasticsearch-driver v3.12.

I'm closing this issue since it's already fixed.

If you still have problems, please leave a comment here asking for re-open.

**Comment by iget-esoares** [comment] 2019-07-02 14:18
@ahxiaowu 

This was a known issue caused by the 7.0 compatibility introduced on 3.11, but since it causes an break change, we reverted it on 3.12 and released the 7.0 support on 4.0.

As suggested by @mathmarques update you dependencies to have scout-elasticsearch-driver v3.12.

I'm closing this issue since it's already fixed.

If you still have problems, please leave a comment here asking for re-open.

**Closed by iget-esoares** 2019-07-02 14:18 UTC

**Comment by raymondtri** [comment] 2019-07-17 18:43
I am on "babenkoivan/scout-elasticsearch-driver": "^4.0" and I am still having this issue. Do I need to revert to 3.12?

**Comment by mathmarques** [comment] 2019-07-17 21:11
@raymondtri Yes, you should use v3 for ES 6.X

**Comment by raymondtri** [comment] 2019-07-18 18:44
My elasticsearch is 7.2 though

**Comment by farshadff** [comment] 2019-09-17 09:58
any solution u found @raymondtri because i have the same problem and its not the issu of compatibility as i have checked that and my ES is 7.1 too
