### ISSUE TITLE
Using shouldBeSearchable triggers a Missing404Exception

### ISSUE THREAD

**Issue by MoogyG** [babenkoivan/scout-elasticsearch-driver#88] opened 2018-05-07 18:13 UTC
I am using `shouldBeSearchable` function, because when my model is created it's in a "draft" state. So after the creation, it's not inserted in elasticsearch.
But if I make an update to this model still in draft state, then it fires a Missing404Exception because shouldBeSearchable  still return false, so the elastic tries to delete it.

I handle this by extending elastic engine like this but for me it should not trigger "delete" event, or it should call a try catch if `shouldBeSearchable` is not empty.

```<?php

use \ScoutElastic\ElasticEngine;

class CustomElasticEngine extends ElasticEngine
{

    public function delete($models)
    {
        try {
            parent::delete($models);
        } catch (\Elasticsearch\Common\Exceptions\Missing404Exception $exception) { }
    }
}
```

**Comment by Lanatel** [comment] 2018-05-16 13:29
Hi, did you solve this problem? Cause I have it too and don't know how to deal with it. 
I already created an issue https://github.com/laravel/scout/issues/280 but didn't get any replies. 
I tried to override an unsearchable method, where I checked if model exists in index or not but it causes a strange elastic behaviour. Sometimes it works properly but sometimes it tries to delete index with wrong _id and I can't understand why it  happens.

**Comment by MoogyG** [comment] 2018-05-16 17:10
@Lanatel  I created the class above and add this code in boot method of my appServiceProvider

```
resolve(EngineManager::class)->extend('customelastic', function () {
           
            // Repris de
            $indexerType = config('scout_elastic.indexer', 'single');
            $updateMapping = config('scout_elastic.update_mapping', true);

            $indexerClass = '\\ScoutElastic\\Indexers\\'.ucfirst($indexerType).'Indexer';

            if (!class_exists($indexerClass)) {
                throw new InvalidArgumentException(sprintf(
                    'The %s indexer doesn\'t exist.',
                    $indexerType
                ));
            }

            return new CustomElasticEngine(new $indexerClass(), $updateMapping);
        });
```

**Comment by babenkoivan** [comment] 2018-05-18 11:36
Hi guys, `shouldBeSearchable` is processed inside scout package. It kind of makes sense to delete model from an index, if it used to be searchable previously. The problem is that in your case it has never been in an index, so delete query returns error. It's not really cool to silence the query, using try/catch, because you still make a query to ES in each model save. 

I haven't made up any proper solution to the problem, so my advice for now is - don't use `shouldBeSearchable`. If you don't need model in an index, just return empty array from `toSearchableArray` method. Note, it won't work if you are using soft deletes configured in the scout package.

**Comment by akos-vomo** [comment] 2018-07-24 10:49
Hey,
is there any progress in this topic?

**Comment by raulduran** [comment] 2018-09-17 20:30
> Hi guys, `shouldBeSearchable` is processed inside scout package. It kind of makes sense to delete model from an index, if it used to be searchable previously. The problem is that in your case it has never been in an index, so delete query returns error. It's not really cool to silence the query, using try/catch, because you still make a query to ES in each model save.
> 
> I haven't made up any proper solution to the problem, so my advice for now is - don't use `shouldBeSearchable`. If you don't need model in an index, just return empty array from `toSearchableArray` method. Note, it won't work if you are using soft deletes configured in the scout package.



> Hi guys, `shouldBeSearchable` is processed inside scout package. It kind of makes sense to delete model from an index, if it used to be searchable previously. The problem is that in your case it has never been in an index, so delete query returns error. It's not really cool to silence the query, using try/catch, because you still make a query to ES in each model save.
> 
> I haven't made up any proper solution to the problem, so my advice for now is - don't use `shouldBeSearchable`. If you don't need model in an index, just return empty array from `toSearchableArray` method. Note, it won't work if you are using soft deletes configured in the scout package.

/**
 * @inheritdoc
 */
public function delete($models)
{
    $this->indexer->delete($models->filter(function ($model) {
       return ElasticClient::exists([
            'id' => $model->id,
            'index' => $model->searchableAs(),
            'type' => $model->searchableAs()
        ]);
    }));
}

**Comment by michaelnguyen547** [comment] 2019-01-15 03:17
encounter exactly same error when using `shouldBeSearchable`, any words on when there is a solution for this in this package?

**Comment by vedmant** [comment] 2019-01-23 17:07
I have the same problem, looks like solution is here above, but when pull request can be merged and published?

**Comment by WouterFlorijn** [comment] 2019-02-08 14:15
Would be great if the solution above could be implemented. The added check makes perfect sense imo. Currently, saving a non-searchable model triggers an error.

**Comment by michaelnguyen547** [comment] 2019-02-21 03:50
@babenkoivan please merge in the PR. A lot of people will be very happy.

**Comment by alexander-rieder** [comment] 2019-02-21 10:06
yes, would be aweomse

**Closed** 2019-02-23 09:04 UTC

**Comment by babenkoivan** [comment] 2019-02-23 13:20
Hi guys, I merged @WouterFlorijn's request. You can now fetch the new `v3.9.1` version.
Thanks for the effort!
