### ISSUE TITLE
How do I boost a document by a field?

### ISSUE THREAD

**Issue by schmolie** [babenkoivan/scout-elasticsearch-driver#50] opened 2018-01-16 07:54 UTC
I have a searchable recipe model and would like recipes with a featured image to appear higher in the results list. 

If I search for pie I want to boost recipes with the word pie and a featured image. I found this https://www.elastic.co/guide/en/elasticsearch/guide/current/boosting-by-popularity.html 
But I’m new at elasticsearch and not sure if this is the best way to go or how to implement it with this package. 

Any help would be very appreciated!

**Comment by babenkoivan** [comment] 2018-01-16 16:16
Hi

First of all you have to store flag (is there image or not) in ES. Then you can use bool queries https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html nested in `should` clause, for first query you search for items by text and image (it will have a higher `boost`), for second - only by text. So items with image will be in the top of results.

This is a draft how I would do that.

**Comment by schmolie** [comment] 2018-01-22 11:01
Hi, thanks for your quick reply! 

I tired doing what you suggested and it worked but not with my ngram analyzer. I'm not able to search parts of words. I tried setting analyzer to nGram_analyzer in my multi_match but it didn't work. Do you have any suggestions? 

My RecipeIndexConfigurator looks like this
```
    protected $settings = [
        "analysis" => [
            "filter" => [
                "nGram_filter" => [
                    "type" => "nGram",
                    "min_gram" => 2,
                    "max_gram" => 20,
                    "token_chars" => [
                        "letter",
                        "digit",
                        "punctuation",
                        "symbol"
                    ]
                ]
            ],
            "analyzer" => [
                "nGram_analyzer" => [
                    "type" => "custom",
                    "tokenizer" => "whitespace",
                    "filter" => [
                        "lowercase",
                        "asciifolding",
                        "nGram_filter"
                    ]
                ],
                "whitespace_analyzer" => [
                    "type" => "custom",
                    "tokenizer" => "whitespace",
                    "filter" => [
                        "lowercase",
                        "asciifolding"
                   ]
                ]
            ]
        ]
    ];

    protected $defaultMapping = [
        "_all" => [
            "analyzer" => "nGram_analyzer",
            "search_analyzer" => "whitespace_analyzer",
        ],
        "properties" => [
            "id" => [
                "type" => "integer",
                "index" => "not_analyzed",
            ],
            "title" => [
                "type" => "text",
            ],
            "summary" => [
                "type" => "text",
            ],
            "username" => [
                "type" => "text",
            ],
            "tag_titles" => [
                "type" => "text",
            ],
            "category_titles" => [
                "type" => "text",
            ],
            "slug" => [
                "type" => "text",
                "include_in_all" => false
            ],
            "featured_image" => [
                "type" => "text",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "visibility" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "plus_members_only" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "rating_avg" => [
                "type" => "integer",
                "include_in_all" => false
            ],
            "num_views" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "tagIds" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "categoryIds" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "kcal" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "fat" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "protein" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
            "carbohydrates" => [
                "type" => "integer",
                "index" => "not_analyzed",
                "include_in_all" => false
            ],
        ]
    ];
```
And my search rule 
```
    return [
            "must" => [
                "multi_match" => [
                    "query" => $this->builder->query,
                    "fields" => ['title', 'category_titles', 'tag_titles', 'summary'],
                ],
            ],
            "should" => [
                "match" => [
                    "has_featured_image" => true
                ]
            ],
            "boost" => 1.0
        ];
```

**Comment by babenkoivan** [comment] 2018-01-28 14:49
I think your search rule should be something like this:

```
[
    'should' => [
        [
            'bool' => [
                'must' => [
                    [
                        'multi_match' => [
                            'query' => $this->builder->query,
                            'fields' => ['title', 'category_titles', 'tag_titles', 'summary']
                        ]
                    ],
                    [
                        'term' => [
                            'has_featured_image' => true
                        ]
                    ]
                ],
                'boost' => 2
            ]
        ],
        [
            'multi_match' => [
                'query' => $this->builder->query,
                'fields' => ['title', 'category_titles', 'tag_titles', 'summary'],
                'boost' => 1
            ]
        ]    
    ],
    'minimum_should_match' => 1
]
```

The idea is that you tell ES to search your data, using 2 clauses with different boosting: 
1. Using search query and image filter
2. Using search query

1st clause has a higher boost, so it should appear in the top of search results.

PS: I didn't test it, this is just an idea how it can be done.

**Comment by babenkoivan** [comment] 2018-03-12 21:33
No feedback from the author.
The issue is closed as outdated.

**Closed by babenkoivan** 2018-03-12 21:33 UTC
