### ISSUE TITLE
Types cannot be provided with es7 and v4 of this package

### ISSUE THREAD

**Issue by farshadff** [babenkoivan/scout-elasticsearch-driver#271] opened 2019-09-17 09:57 UTC
hi guys i am trying to run this command 
```
php artisan elastic:update-mapping "App\Classname"
```
but i get this error :
```
  Elasticsearch\Common\Exceptions\BadRequest400Exception  : {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}
```
now i read the compatibilites version on issues so i down grade to v 3.4 driver but it didnt work and tried with v4 but no luck again . my elastic is number: "7.1.1",

**Comment by iget-master** [comment] 2019-09-17 10:01
Types are deprecated on ES7. See https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0

**Comment by farshadff** [comment] 2019-09-17 10:06
so what should i do now ???

**Comment by vpillinger** [comment] 2019-10-08 20:48
You don't need to specify types, just put each model in its own index. Or share them in the same index, but don't mix property names up. (Ie, an id property must either be an int or a string, but sometimes one and sometimes another)

**Comment by iget-esoares** [comment] 2019-12-28 18:20
Closing this issue since that's not a bug on this package, but a deprecation of Elasticsearch

**Closed** 2019-12-28 18:19 UTC
