### ISSUE TITLE
'multi_match'- and more, beside 'bool' queries

### ISSUE THREAD

**Issue by ametad** [babenkoivan/scout-elasticsearch-driver#13] opened 2017-09-14 10:50 UTC
First of all, nice work this plugin!

As I am getting to know this plugin step by step, I notice that all queries (beside raw searches of course) are 'bool' queries. Is this correct, or do I overlook something?

In trying to get better searches I want to use 'multi_match' queries like this:

```
{
  "query": {
    "multi_match": {
      "type":     "most_fields",
      "query":    "administreur",
      "minimum_should_match": "80%",
      "fields": [ "title", "title.dutch", "description", "description.dutch" ]
    }
  }
}
```

Kind regards.

**Comment by babenkoivan** [comment] 2017-09-14 11:09
Hi @ametad, yes, you are right, all the queries are bool queries. You can use `multi_match` inside a bool query like following:

```
{
    "query": {
        "bool" => {
            "must" => {
                "multi_match": {
                    "type":     "most_fields",
                    "query":    "administreur",
                    "minimum_should_match": "80%",
                    "fields": [ "title", "title.dutch", "description", "description.dutch" ]
                }
            }
        }
    }
}
```
To achieve that use [search rules](https://github.com/babenkoivan/scout-elasticsearch-driver#search-rules). Hope it will work for you!

**Comment by ametad** [comment] 2017-09-14 11:44
Thank you Ivan! Your suggestion is indeed a way to use multi_match queries. The search rules I have in use already ;-)

**Comment by sempixel** [comment] 2017-09-27 12:25
True life saver. This should be hinted in README.

**Comment by ametad** [comment] 2017-10-02 10:30
@babenkoivan The way it is implemented now, you must always use 'bool' queries. Do you perhaps have plans to refactor, so more customized queries could be build without always using the 'bool' queries as root?

From the docs https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-multi-match-query.html#type-most-fields

This query:

```
GET /_search
{
  "query": {
    "multi_match" : {
      "query":      "quick brown fox",
      "type":       "most_fields",
      "fields":     [ "title", "title.original", "title.shingles" ]
    }
  }
}
```

would be executed as:

```
GET /_search
{
  "query": {
    "bool": {
      "should": [
        { "match": { "title":          "quick brown fox" }},
        { "match": { "title.original": "quick brown fox" }},
        { "match": { "title.shingles": "quick brown fox" }}
      ]
    }
  }
}
```

But with the current implementation of this plugin, I am not sure how this would become :

```
GET /_search
{
  "query": {
    "bool": {
      "must": [
        "multi_match" : { // Multi match within a must bool query...
          "query":      "quick brown fox",
          "type":       "most_fields",
          "fields":     [ "title", "title.original", "title.shingles" ]
        }
      ]
    }
  }
}
```

**Comment by babenkoivan** [comment] 2017-10-03 10:07
Hi @ametad, maybe it's a good idea to give users an opportunity to create search rules with any type of queries as a root. But actually I can't see a problem here, because you can always wrap your query in a bool query and it'll work as it was designed. Your example above looks fine, it should work. I understand that maybe it's not convenient or tricky, but I don't understand why you can't use a bool query in your situation..

**Comment by ametad** [comment] 2017-10-05 09:35
@babenkoivan Thank you for your answer. I am fairly new to Elasticsearch so I have to rely on your knowledge for the most part... Why do you think it "will work as it was designed"?  
I am thinking that perhaps the query executed will have boolean queries inside boolean queries (if such is possible)...

**Comment by babenkoivan** [comment] 2017-10-07 19:35
> Why do you think it "will work as it was designed"?
Because you can read it in the documentation, also it's my experience of working with ES and at last you can check it by yourself 😉

**Comment by vincentsch** [comment] 2017-10-25 14:17
Hi @babenkoivan, FOA, thank you for this driver, it's by far the best Elasticsearch Scout driver out there.

Above, you wrote

> you can always wrap your query in a bool query

However, this is not true for the completion suggester ([link](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html)). (In earlier Elastic versions there used to be a _suggest endpoint. This was dropped in favor of the _search endpoint.)

Here's an example from the docs:
`POST music/_search?pretty
{
    "suggest": {
        "song-suggest" : {
            "prefix" : "nir", 
            "completion" : { 
                "field" : "suggest" 
            }
        }
    }
}`

Currently, there's no way to make the above request with the current implementation of SearchRules.

**Comment by babenkoivan** [comment] 2017-10-27 18:03
Hi @vincentsch, sorry for the late reply. This is a good example, I'll have to think about how to improve search rules  and not to break everything :)

**Comment by babenkoivan** [comment] 2018-01-28 13:26
Hey @vincentsch, I had a closer look at suggesters and it turned out, that suggesters are not a part of query. According to the docs: 

> The suggest request part is defined alongside the query part in a _search request.

So if suggesters support is required, please create a new issue for that. 

As for the current issue, I'm still pretty sure, that you can wrap almost everything in a bool query. Also it can be difficult to use filters (where clauses) with some types of search queries (not bool queries), because they can be not supported. I leave this issue opened for further discussion.

**Comment by vincentsch** [comment] 2018-01-29 07:55
@babenkoivan Thank you! That should be fine as you can do it with a raw query.

Here's some code if someone finds this thread looking for a solution:

`$results = \App\SomeModel::searchRaw([
	'suggest' => [
		'text' => $search_term,
		'column1' => [
			'completion' => [
				'field' => 'column1.suggest'
			]
		],
		'column2' => [
			'completion' => [
				'field' => 'column2.suggest'
			]
		]
	]
]);`

As far as I'm concerned you can close this ticket.

**Closed** 2018-01-29 08:23 UTC
